server:
  port: 8761 # Standard Eureka port

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # It is the server, so it doesn't register itself
    fetch-registry: false       # It doesn't need to fetch the registry
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/